// Seed data for the family-api. Copied faithfully from the client apps'
// original local seed files:
//   - recipes: ~/workspace/apps/dinner-menu/src/data/recipes.js (SEED_RECIPES)
//   - questions: ~/workspace/apps/trivia-night/src/questions.js (SEED_QUESTIONS)

const SEED_RECIPES = [
  {
    name: 'Smash Burgers',
    time: '~30 min',
    ingredients: [
      '1.5 lb ground beef (80/20)',
      '8 burger buns',
      'Cheese slices',
      'Tomatoes',
      'Yellow onion',
      'Dill pickles',
      'Lettuce',
      'Frozen fries',
      'Salt',
      'Pepper',
      'Oil',
      'Ketchup',
      'Mustard',
      'Mayo',
    ],
    steps: [
      'Get the fries in the oven at 425°F for 20–25 minutes, flipping them halfway.',
      'Divide the beef into 8 loose balls — don’t pack them tight.',
      'Heat an oiled cast-iron skillet until it’s screaming hot.',
      'Smash 2–3 balls flat (a sheet of parchment between spatula and meat keeps it from sticking), season with salt and pepper, and cook 2 minutes untouched.',
      'Flip, top with cheese immediately, and cook 1 more minute.',
      'Toast the buns cut-side down in the beefy pan.',
      'Assemble with tomato, onion, pickles, lettuce, and condiments, and serve with the fries.',
    ],
    tip: 'Press only once at the start — pressing later squeezes out all the juice.',
  },
  {
    name: 'Turkey Meatballs in Gravy',
    time: '4h (crockpot, low)',
    ingredients: [
      'Ground turkey',
      'Breadcrumbs',
      'Egg',
      'Onion',
      'Salt',
      'Pepper',
      'Garlic powder',
      'Flour',
      'Beef broth',
      'Egg noodles',
    ],
    steps: [
      'Thaw the turkey if frozen.',
      'Mix it with ½ cup breadcrumbs, 1 egg, half a diced onion, salt, pepper, and garlic powder.',
      'Roll into balls and drop them into the crockpot.',
      'Whisk 2 tbsp flour into 2 cups beef broth and pour over the meatballs.',
      'Cook on low for 4 hours.',
      'Serve over egg noodles.',
    ],
    tip: '',
  },
  {
    name: 'Honey Garlic Chicken Breast',
    time: '~20 min',
    ingredients: [
      'Chicken breasts',
      'Honey',
      'Soy sauce',
      'Garlic',
      'Rice',
      'Broccoli',
      'Oil',
    ],
    steps: [
      'Thaw the chicken and cut it into bite-size pieces.',
      'Sear in an oiled skillet for 5–6 minutes.',
      'Stir together ⅓ cup honey, ¼ cup soy sauce, and 4 minced garlic cloves.',
      'Pour the sauce over the chicken and simmer 5 minutes, until glossy.',
      'Serve over rice with steamed broccoli.',
    ],
    tip: 'Don’t overcook the breast — that’s the whole game.',
  },
  {
    name: 'Black Bean & Corn Burritos',
    time: '~25 min',
    ingredients: [
      'Rice',
      'Black beans',
      'Corn',
      'Onion',
      'Salsa',
      'Cumin',
      'Chili powder',
      'Flour tortillas',
      'Shredded cheese',
      'Sour cream',
    ],
    steps: [
      'Cook the rice.',
      'Sauté a diced onion until soft.',
      'Add drained beans and corn, plus half the salsa and a shake of cumin and chili powder. Heat through.',
      'Warm the tortillas so they don’t crack.',
      'Fill with rice, the bean mix, cheese, and sour cream; roll up.',
    ],
    tip: 'Optional: crisp the rolled burritos in a dry skillet until golden on each side.',
  },
  {
    name: "Shepherd's Pie",
    time: '~40 min',
    ingredients: [
      '1.5 lb ground beef',
      'Onion',
      'Frozen mixed veg',
      'Beef broth',
      'Potatoes',
      'Butter',
      'Milk',
      'Salt',
      'Shredded cheddar',
    ],
    steps: [
      'Brown the beef with a diced onion; drain off the fat.',
      'Stir in the frozen mixed veg and ½ cup beef broth; simmer 5 minutes.',
      'Boil cubed potatoes until tender, then mash with butter, milk, and salt.',
      'Spread the beef mixture in a baking dish, top with the mash, and sprinkle cheddar over everything.',
      'Bake at 400°F for 20 minutes, until golden on top.',
    ],
    tip: '',
  },
];

const SEED_QUESTIONS = [
  // ---- easy (Briar Easy: Bluey, colors, animals) ----
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What color is Bluey\u2019s fur?', answer: 'Blue! She\u2019s a blue heeler.' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What is Bluey\u2019s little sister called?', answer: 'Bingo' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What is Bluey\u2019s mom\u2019s name?', answer: 'Chilli' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What do you get when you mix blue and yellow?', answer: 'Green' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What color is a ripe strawberry?', answer: 'Red' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What animal says "moo"?', answer: 'A cow' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'How many legs does a spider have?', answer: 'Eight' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What do bees make?', answer: 'Honey' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What animal is the fastest runner on land?', answer: 'The cheetah' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What do you call a baby dog?', answer: 'A puppy' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'What color is the sun in most drawings?', answer: 'Yellow' },
  { tier: 'easy', topic: 'Bluey, Colors & Animals', text: 'Which animal has a long trunk?', answer: 'The elephant' },

  // ---- medium (Wyatt & Pepper Medium: history, movies, science) ----
  { tier: 'medium', topic: 'History, Movies & Science', text: 'What does the "D" in D-Day stand for?', answer: 'Trick question \u2014 it doesn\u2019t stand for anything! The "D" just means "day."' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'In which country did the D-Day landings happen?', answer: 'France (on the beaches of Normandy)' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'What planet is known as the Red Planet?', answer: 'Mars' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'In "Frozen," what is the snowman\u2019s name?', answer: 'Olaf' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'How many dwarfs help Snow White?', answer: 'Seven' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'What is the name of Moana\u2019s silly chicken?', answer: 'Heihei' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'In "The Lion King," what is Simba\u2019s dad\u2019s name?', answer: 'Mufasa' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'What force pulls everything down toward the Earth?', answer: 'Gravity' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'Which is the biggest ocean in the world?', answer: 'The Pacific Ocean' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'About how many days does it take Earth to orbit the Sun?', answer: '365 days' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'In Trolls, what are the grumpy giants who want to eat the Trolls called?', answer: 'Bergens' },
  { tier: 'medium', topic: 'History, Movies & Science', text: 'What do plants need to make their food? (Name two!)', answer: 'Sunlight, water, and air \u2014 any two counts!' },

  // ---- hard (Grown-Up Hard: 80s movies, music, books) ----
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'In "Back to the Future," how fast must the DeLorean go to time travel?', answer: '88 miles per hour' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'In "Ghostbusters," what do they warn you should NEVER do?', answer: 'Cross the streams' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'What does Inigo Montoya always say before a duel in "The Princess Bride"?', answer: '"Hello. My name is Inigo Montoya. You killed my father. Prepare to die."' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'In "Ferris Bueller\u2019s Day Off," what kind of car does Cameron\u2019s dad own?', answer: 'A 1961 Ferrari 250 GT' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'Which 1986 Tom Cruise movie made everyone want to be a fighter pilot?', answer: '"Top Gun"' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'Which quiet acoustic Led Zeppelin instrumental closes out Philip\u2019s mix tapes?', answer: '"Bron-Yr-Aur" (from Physical Graffiti)' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'Which Led Zeppelin album cover shows a man carrying a bundle of sticks?', answer: '"Led Zeppelin IV"' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'Jimmy Buffett\u2019s most famous song is about wasting away in which fictional place?', answer: 'Margaritaville' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'Phish\u2019s devoted fanbase is most often compared to the followers of which band?', answer: 'The Grateful Dead' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'Which Stephen King novel features a killer clown named Pennywise?', answer: '"It"' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'In Stephen King\u2019s "The Shining," what word does Danny keep repeating?', answer: '"Redrum"' },
  { tier: 'hard', topic: '80s Movies, Music & Books', text: 'David Foster Wallace\u2019s "Infinite Jest" is famous for what structural quirk?', answer: 'Its enormous endnotes \u2014 nearly 100 pages of footnotes!' },
];

module.exports = { SEED_RECIPES, SEED_QUESTIONS };
